package agentgatewaysyncer

const (
	TargetTypeResourceUrl = "type.googleapis.com/agentgateway.dev.resource.Resource"
	TargetTypeAddressUrl  = "type.googleapis.com/agentgateway.dev.workload.Address"
	AgentgatewayName      = "agentgateway-autogenerated-k8s-gateway"
)
