// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// AiExtensionTraceApplyConfiguration represents a declarative configuration of the AiExtensionTrace type for use
// with apply.
type AiExtensionTraceApplyConfiguration struct {
	EndPoint          *v1.AbsoluteURI                        `json:"endpoint,omitempty"`
	Sampler           *OTelTracesSamplerApplyConfiguration   `json:"sampler,omitempty"`
	Timeout           *v1.Duration                           `json:"timeout,omitempty"`
	Protocol          *apiv1alpha1.OTLPTracesProtocolType    `json:"protocol,omitempty"`
	TransportSecurity *apiv1alpha1.OTLPTransportSecurityMode `json:"transportSecurity,omitempty"`
}

// AiExtensionTraceApplyConfiguration constructs a declarative configuration of the AiExtensionTrace type for use with
// apply.
func AiExtensionTrace() *AiExtensionTraceApplyConfiguration {
	return &AiExtensionTraceApplyConfiguration{}
}

// WithEndPoint sets the EndPoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndPoint field is set to the value of the last call.
func (b *AiExtensionTraceApplyConfiguration) WithEndPoint(value v1.AbsoluteURI) *AiExtensionTraceApplyConfiguration {
	b.EndPoint = &value
	return b
}

// WithSampler sets the Sampler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sampler field is set to the value of the last call.
func (b *AiExtensionTraceApplyConfiguration) WithSampler(value *OTelTracesSamplerApplyConfiguration) *AiExtensionTraceApplyConfiguration {
	b.Sampler = value
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *AiExtensionTraceApplyConfiguration) WithTimeout(value v1.Duration) *AiExtensionTraceApplyConfiguration {
	b.Timeout = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *AiExtensionTraceApplyConfiguration) WithProtocol(value apiv1alpha1.OTLPTracesProtocolType) *AiExtensionTraceApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithTransportSecurity sets the TransportSecurity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TransportSecurity field is set to the value of the last call.
func (b *AiExtensionTraceApplyConfiguration) WithTransportSecurity(value apiv1alpha1.OTLPTransportSecurityMode) *AiExtensionTraceApplyConfiguration {
	b.TransportSecurity = &value
	return b
}
