// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// AiExtensionTraceApplyConfiguration represents a declarative configuration of the AiExtensionTrace type for use
// with apply.
type AiExtensionTraceApplyConfiguration struct {
	Enabled     *bool          `json:"enabled,omitempty"`
	ServiceName *string        `json:"servicename,omitempty"`
	Address     *string        `json:"address,omitempty"`
	Port        *v1.PortNumber `json:"port,omitempty"`
}

// AiExtensionTraceApplyConfiguration constructs a declarative configuration of the AiExtensionTrace type for use with
// apply.
func AiExtensionTrace() *AiExtensionTraceApplyConfiguration {
	return &AiExtensionTraceApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *AiExtensionTraceApplyConfiguration) WithEnabled(value bool) *AiExtensionTraceApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithServiceName sets the ServiceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceName field is set to the value of the last call.
func (b *AiExtensionTraceApplyConfiguration) WithServiceName(value string) *AiExtensionTraceApplyConfiguration {
	b.ServiceName = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *AiExtensionTraceApplyConfiguration) WithAddress(value string) *AiExtensionTraceApplyConfiguration {
	b.Address = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *AiExtensionTraceApplyConfiguration) WithPort(value v1.PortNumber) *AiExtensionTraceApplyConfiguration {
	b.Port = &value
	return b
}
