// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AnyValueApplyConfiguration represents a declarative configuration of the AnyValue type for use
// with apply.
type AnyValueApplyConfiguration struct {
	StringValue *string                            `json:"stringValue,omitempty"`
	ArrayValue  []AnyValueApplyConfiguration       `json:"arrayValue,omitempty"`
	KvListValue *KeyAnyValueListApplyConfiguration `json:"kvListValue,omitempty"`
}

// AnyValueApplyConfiguration constructs a declarative configuration of the AnyValue type for use with
// apply.
func AnyValue() *AnyValueApplyConfiguration {
	return &AnyValueApplyConfiguration{}
}

// WithStringValue sets the StringValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StringValue field is set to the value of the last call.
func (b *AnyValueApplyConfiguration) WithStringValue(value string) *AnyValueApplyConfiguration {
	b.StringValue = &value
	return b
}

// WithArrayValue adds the given value to the ArrayValue field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ArrayValue field.
func (b *AnyValueApplyConfiguration) WithArrayValue(values ...*AnyValueApplyConfiguration) *AnyValueApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithArrayValue")
		}
		b.ArrayValue = append(b.ArrayValue, *values[i])
	}
	return b
}

// WithKvListValue sets the KvListValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KvListValue field is set to the value of the last call.
func (b *AnyValueApplyConfiguration) WithKvListValue(value *KeyAnyValueListApplyConfiguration) *AnyValueApplyConfiguration {
	b.KvListValue = value
	return b
}
