// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AWSGuardrailConfigApplyConfiguration represents a declarative configuration of the AWSGuardrailConfig type for use
// with apply.
type AWSGuardrailConfigApplyConfiguration struct {
	GuardrailIdentifier *string `json:"identifier,omitempty"`
	GuardrailVersion    *string `json:"version,omitempty"`
}

// AWSGuardrailConfigApplyConfiguration constructs a declarative configuration of the AWSGuardrailConfig type for use with
// apply.
func AWSGuardrailConfig() *AWSGuardrailConfigApplyConfiguration {
	return &AWSGuardrailConfigApplyConfiguration{}
}

// WithGuardrailIdentifier sets the GuardrailIdentifier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GuardrailIdentifier field is set to the value of the last call.
func (b *AWSGuardrailConfigApplyConfiguration) WithGuardrailIdentifier(value string) *AWSGuardrailConfigApplyConfiguration {
	b.GuardrailIdentifier = &value
	return b
}

// WithGuardrailVersion sets the GuardrailVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GuardrailVersion field is set to the value of the last call.
func (b *AWSGuardrailConfigApplyConfiguration) WithGuardrailVersion(value string) *AWSGuardrailConfigApplyConfiguration {
	b.GuardrailVersion = &value
	return b
}
