// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// BufferApplyConfiguration represents a declarative configuration of the Buffer type for use
// with apply.
type BufferApplyConfiguration struct {
	MaxRequestSize *resource.Quantity `json:"maxRequestSize,omitempty"`
}

// BufferApplyConfiguration constructs a declarative configuration of the Buffer type for use with
// apply.
func Buffer() *BufferApplyConfiguration {
	return &BufferApplyConfiguration{}
}

// WithMaxRequestSize sets the MaxRequestSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxRequestSize field is set to the value of the last call.
func (b *BufferApplyConfiguration) WithMaxRequestSize(value resource.Quantity) *BufferApplyConfiguration {
	b.MaxRequestSize = &value
	return b
}
