// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// CustomAttributeMetadataApplyConfiguration represents a declarative configuration of the CustomAttributeMetadata type for use
// with apply.
type CustomAttributeMetadataApplyConfiguration struct {
	Kind         *apiv1alpha1.MetadataKind      `json:"kind,omitempty"`
	MetadataKey  *MetadataKeyApplyConfiguration `json:"metadataKey,omitempty"`
	DefaultValue *string                        `json:"defaultValue,omitempty"`
}

// CustomAttributeMetadataApplyConfiguration constructs a declarative configuration of the CustomAttributeMetadata type for use with
// apply.
func CustomAttributeMetadata() *CustomAttributeMetadataApplyConfiguration {
	return &CustomAttributeMetadataApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *CustomAttributeMetadataApplyConfiguration) WithKind(value apiv1alpha1.MetadataKind) *CustomAttributeMetadataApplyConfiguration {
	b.Kind = &value
	return b
}

// WithMetadataKey sets the MetadataKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetadataKey field is set to the value of the last call.
func (b *CustomAttributeMetadataApplyConfiguration) WithMetadataKey(value *MetadataKeyApplyConfiguration) *CustomAttributeMetadataApplyConfiguration {
	b.MetadataKey = value
	return b
}

// WithDefaultValue sets the DefaultValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultValue field is set to the value of the last call.
func (b *CustomAttributeMetadataApplyConfiguration) WithDefaultValue(value string) *CustomAttributeMetadataApplyConfiguration {
	b.DefaultValue = &value
	return b
}
