// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CustomAttributeLiteralApplyConfiguration represents a declarative configuration of the CustomAttributeLiteral type for use
// with apply.
type CustomAttributeLiteralApplyConfiguration struct {
	Value *string `json:"value,omitempty"`
}

// CustomAttributeLiteralApplyConfiguration constructs a declarative configuration of the CustomAttributeLiteral type for use with
// apply.
func CustomAttributeLiteral() *CustomAttributeLiteralApplyConfiguration {
	return &CustomAttributeLiteralApplyConfiguration{}
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *CustomAttributeLiteralApplyConfiguration) WithValue(value string) *CustomAttributeLiteralApplyConfiguration {
	b.Value = &value
	return b
}
