// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CustomAttributeEnvironmentApplyConfiguration represents a declarative configuration of the CustomAttributeEnvironment type for use
// with apply.
type CustomAttributeEnvironmentApplyConfiguration struct {
	Name         *string `json:"name,omitempty"`
	DefaultValue *string `json:"defaultValue,omitempty"`
}

// CustomAttributeEnvironmentApplyConfiguration constructs a declarative configuration of the CustomAttributeEnvironment type for use with
// apply.
func CustomAttributeEnvironment() *CustomAttributeEnvironmentApplyConfiguration {
	return &CustomAttributeEnvironmentApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CustomAttributeEnvironmentApplyConfiguration) WithName(value string) *CustomAttributeEnvironmentApplyConfiguration {
	b.Name = &value
	return b
}

// WithDefaultValue sets the DefaultValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultValue field is set to the value of the last call.
func (b *CustomAttributeEnvironmentApplyConfiguration) WithDefaultValue(value string) *CustomAttributeEnvironmentApplyConfiguration {
	b.DefaultValue = &value
	return b
}
