// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CustomAttributeHeaderApplyConfiguration represents a declarative configuration of the CustomAttributeHeader type for use
// with apply.
type CustomAttributeHeaderApplyConfiguration struct {
	Name         *string `json:"name,omitempty"`
	DefaultValue *string `json:"defaultValue,omitempty"`
}

// CustomAttributeHeaderApplyConfiguration constructs a declarative configuration of the CustomAttributeHeader type for use with
// apply.
func CustomAttributeHeader() *CustomAttributeHeaderApplyConfiguration {
	return &CustomAttributeHeaderApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CustomAttributeHeaderApplyConfiguration) WithName(value string) *CustomAttributeHeaderApplyConfiguration {
	b.Name = &value
	return b
}

// WithDefaultValue sets the DefaultValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultValue field is set to the value of the last call.
func (b *CustomAttributeHeaderApplyConfiguration) WithDefaultValue(value string) *CustomAttributeHeaderApplyConfiguration {
	b.DefaultValue = &value
	return b
}
