// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EnvoyHealthCheckApplyConfiguration represents a declarative configuration of the EnvoyHealthCheck type for use
// with apply.
type EnvoyHealthCheckApplyConfiguration struct {
	Path *string `json:"path,omitempty"`
}

// EnvoyHealthCheckApplyConfiguration constructs a declarative configuration of the EnvoyHealthCheck type for use with
// apply.
func EnvoyHealthCheck() *EnvoyHealthCheckApplyConfiguration {
	return &EnvoyHealthCheckApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *EnvoyHealthCheckApplyConfiguration) WithPath(value string) *EnvoyHealthCheckApplyConfiguration {
	b.Path = &value
	return b
}
