// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// ExtProcProviderApplyConfiguration represents a declarative configuration of the ExtProcProvider type for use
// with apply.
type ExtProcProviderApplyConfiguration struct {
	BackendRef *v1.BackendRef `json:"backendRef,omitempty"`
}

// ExtProcProviderApplyConfiguration constructs a declarative configuration of the ExtProcProvider type for use with
// apply.
func ExtProcProvider() *ExtProcProviderApplyConfiguration {
	return &ExtProcProviderApplyConfiguration{}
}

// WithBackendRef sets the BackendRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendRef field is set to the value of the last call.
func (b *ExtProcProviderApplyConfiguration) WithBackendRef(value v1.BackendRef) *ExtProcProviderApplyConfiguration {
	b.BackendRef = &value
	return b
}
