// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FullPathOverrideApplyConfiguration represents a declarative configuration of the FullPathOverride type for use
// with apply.
type FullPathOverrideApplyConfiguration struct {
	Path       *string `json:"path,omitempty"`
	Prefix     *string `json:"prefix,omitempty"`
	HeaderName *string `json:"headerName,omitempty"`
}

// FullPathOverrideApplyConfiguration constructs a declarative configuration of the FullPathOverride type for use with
// apply.
func FullPathOverride() *FullPathOverrideApplyConfiguration {
	return &FullPathOverrideApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *FullPathOverrideApplyConfiguration) WithPath(value string) *FullPathOverrideApplyConfiguration {
	b.Path = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *FullPathOverrideApplyConfiguration) WithPrefix(value string) *FullPathOverrideApplyConfiguration {
	b.Prefix = &value
	return b
}

// WithHeaderName sets the HeaderName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeaderName field is set to the value of the last call.
func (b *FullPathOverrideApplyConfiguration) WithHeaderName(value string) *FullPathOverrideApplyConfiguration {
	b.HeaderName = &value
	return b
}
