// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HeaderApplyConfiguration represents a declarative configuration of the Header type for use
// with apply.
type HeaderApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// HeaderApplyConfiguration constructs a declarative configuration of the Header type for use with
// apply.
func Header() *HeaderApplyConfiguration {
	return &HeaderApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HeaderApplyConfiguration) WithName(value string) *HeaderApplyConfiguration {
	b.Name = &value
	return b
}
