// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HeaderValueApplyConfiguration represents a declarative configuration of the HeaderValue type for use
// with apply.
type HeaderValueApplyConfiguration struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// HeaderValueApplyConfiguration constructs a declarative configuration of the HeaderValue type for use with
// apply.
func HeaderValue() *HeaderValueApplyConfiguration {
	return &HeaderValueApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *HeaderValueApplyConfiguration) WithKey(value string) *HeaderValueApplyConfiguration {
	b.Key = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *HeaderValueApplyConfiguration) WithValue(value string) *HeaderValueApplyConfiguration {
	b.Value = &value
	return b
}
