// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HealthCheckHttpApplyConfiguration represents a declarative configuration of the HealthCheckHttp type for use
// with apply.
type HealthCheckHttpApplyConfiguration struct {
	Host   *string `json:"host,omitempty"`
	Path   *string `json:"path,omitempty"`
	Method *string `json:"method,omitempty"`
}

// HealthCheckHttpApplyConfiguration constructs a declarative configuration of the HealthCheckHttp type for use with
// apply.
func HealthCheckHttp() *HealthCheckHttpApplyConfiguration {
	return &HealthCheckHttpApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *HealthCheckHttpApplyConfiguration) WithHost(value string) *HealthCheckHttpApplyConfiguration {
	b.Host = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *HealthCheckHttpApplyConfiguration) WithPath(value string) *HealthCheckHttpApplyConfiguration {
	b.Path = &value
	return b
}

// WithMethod sets the Method field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Method field is set to the value of the last call.
func (b *HealthCheckHttpApplyConfiguration) WithMethod(value string) *HealthCheckHttpApplyConfiguration {
	b.Method = &value
	return b
}
