// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HealthCheckGrpcApplyConfiguration represents a declarative configuration of the HealthCheckGrpc type for use
// with apply.
type HealthCheckGrpcApplyConfiguration struct {
	ServiceName *string `json:"serviceName,omitempty"`
	Authority   *string `json:"authority,omitempty"`
}

// HealthCheckGrpcApplyConfiguration constructs a declarative configuration of the HealthCheckGrpc type for use with
// apply.
func HealthCheckGrpc() *HealthCheckGrpcApplyConfiguration {
	return &HealthCheckGrpcApplyConfiguration{}
}

// WithServiceName sets the ServiceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceName field is set to the value of the last call.
func (b *HealthCheckGrpcApplyConfiguration) WithServiceName(value string) *HealthCheckGrpcApplyConfiguration {
	b.ServiceName = &value
	return b
}

// WithAuthority sets the Authority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authority field is set to the value of the last call.
func (b *HealthCheckGrpcApplyConfiguration) WithAuthority(value string) *HealthCheckGrpcApplyConfiguration {
	b.Authority = &value
	return b
}
