// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// Http1ProtocolOptionsApplyConfiguration represents a declarative configuration of the Http1ProtocolOptions type for use
// with apply.
type Http1ProtocolOptionsApplyConfiguration struct {
	EnableTrailers                          *bool `json:"enableTrailers,omitempty"`
	PreserveHttp1HeaderCase                 *bool `json:"preserveHttp1HeaderCase,omitempty"`
	OverrideStreamErrorOnInvalidHttpMessage *bool `json:"overrideStreamErrorOnInvalidHttpMessage,omitempty"`
}

// Http1ProtocolOptionsApplyConfiguration constructs a declarative configuration of the Http1ProtocolOptions type for use with
// apply.
func Http1ProtocolOptions() *Http1ProtocolOptionsApplyConfiguration {
	return &Http1ProtocolOptionsApplyConfiguration{}
}

// WithEnableTrailers sets the EnableTrailers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableTrailers field is set to the value of the last call.
func (b *Http1ProtocolOptionsApplyConfiguration) WithEnableTrailers(value bool) *Http1ProtocolOptionsApplyConfiguration {
	b.EnableTrailers = &value
	return b
}

// WithPreserveHttp1HeaderCase sets the PreserveHttp1HeaderCase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PreserveHttp1HeaderCase field is set to the value of the last call.
func (b *Http1ProtocolOptionsApplyConfiguration) WithPreserveHttp1HeaderCase(value bool) *Http1ProtocolOptionsApplyConfiguration {
	b.PreserveHttp1HeaderCase = &value
	return b
}

// WithOverrideStreamErrorOnInvalidHttpMessage sets the OverrideStreamErrorOnInvalidHttpMessage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OverrideStreamErrorOnInvalidHttpMessage field is set to the value of the last call.
func (b *Http1ProtocolOptionsApplyConfiguration) WithOverrideStreamErrorOnInvalidHttpMessage(value bool) *Http1ProtocolOptionsApplyConfiguration {
	b.OverrideStreamErrorOnInvalidHttpMessage = &value
	return b
}
