// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// KeyAnyValueListApplyConfiguration represents a declarative configuration of the KeyAnyValueList type for use
// with apply.
type KeyAnyValueListApplyConfiguration struct {
	Values []KeyAnyValueApplyConfiguration `json:"values,omitempty"`
}

// KeyAnyValueListApplyConfiguration constructs a declarative configuration of the KeyAnyValueList type for use with
// apply.
func KeyAnyValueList() *KeyAnyValueListApplyConfiguration {
	return &KeyAnyValueListApplyConfiguration{}
}

// WithValues adds the given value to the Values field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Values field.
func (b *KeyAnyValueListApplyConfiguration) WithValues(values ...*KeyAnyValueApplyConfiguration) *KeyAnyValueListApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithValues")
		}
		b.Values = append(b.Values, *values[i])
	}
	return b
}
