// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ListenerPolicySpecApplyConfiguration represents a declarative configuration of the ListenerPolicySpec type for use
// with apply.
type ListenerPolicySpecApplyConfiguration struct {
	TargetRefs                    []LocalPolicyTargetReferenceApplyConfiguration `json:"targetRefs,omitempty"`
	PerConnectionBufferLimitBytes *uint32                                        `json:"perConnectionBufferLimitBytes,omitempty"`
}

// ListenerPolicySpecApplyConfiguration constructs a declarative configuration of the ListenerPolicySpec type for use with
// apply.
func ListenerPolicySpec() *ListenerPolicySpecApplyConfiguration {
	return &ListenerPolicySpecApplyConfiguration{}
}

// WithTargetRefs adds the given value to the TargetRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetRefs field.
func (b *ListenerPolicySpecApplyConfiguration) WithTargetRefs(values ...*LocalPolicyTargetReferenceApplyConfiguration) *ListenerPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetRefs")
		}
		b.TargetRefs = append(b.TargetRefs, *values[i])
	}
	return b
}

// WithPerConnectionBufferLimitBytes sets the PerConnectionBufferLimitBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PerConnectionBufferLimitBytes field is set to the value of the last call.
func (b *ListenerPolicySpecApplyConfiguration) WithPerConnectionBufferLimitBytes(value uint32) *ListenerPolicySpecApplyConfiguration {
	b.PerConnectionBufferLimitBytes = &value
	return b
}
