// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LoadBalancerLeastRequestConfigApplyConfiguration represents a declarative configuration of the LoadBalancerLeastRequestConfig type for use
// with apply.
type LoadBalancerLeastRequestConfigApplyConfiguration struct {
	ChoiceCount     *uint32                            `json:"choiceCount,omitempty"`
	SlowStartConfig *SlowStartConfigApplyConfiguration `json:"slowStartConfig,omitempty"`
}

// LoadBalancerLeastRequestConfigApplyConfiguration constructs a declarative configuration of the LoadBalancerLeastRequestConfig type for use with
// apply.
func LoadBalancerLeastRequestConfig() *LoadBalancerLeastRequestConfigApplyConfiguration {
	return &LoadBalancerLeastRequestConfigApplyConfiguration{}
}

// WithChoiceCount sets the ChoiceCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ChoiceCount field is set to the value of the last call.
func (b *LoadBalancerLeastRequestConfigApplyConfiguration) WithChoiceCount(value uint32) *LoadBalancerLeastRequestConfigApplyConfiguration {
	b.ChoiceCount = &value
	return b
}

// WithSlowStartConfig sets the SlowStartConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SlowStartConfig field is set to the value of the last call.
func (b *LoadBalancerLeastRequestConfigApplyConfiguration) WithSlowStartConfig(value *SlowStartConfigApplyConfiguration) *LoadBalancerLeastRequestConfigApplyConfiguration {
	b.SlowStartConfig = value
	return b
}
