// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// LoadBalancerApplyConfiguration represents a declarative configuration of the LoadBalancer type for use
// with apply.
type LoadBalancerApplyConfiguration struct {
	HealthyPanicThreshold           *uint32                                           `json:"healthyPanicThreshold,omitempty"`
	UpdateMergeWindow               *v1.Duration                                      `json:"updateMergeWindow,omitempty"`
	LeastRequest                    *LoadBalancerLeastRequestConfigApplyConfiguration `json:"leastRequest,omitempty"`
	RoundRobin                      *LoadBalancerRoundRobinConfigApplyConfiguration   `json:"roundRobin,omitempty"`
	RingHash                        *LoadBalancerRingHashConfigApplyConfiguration     `json:"ringHash,omitempty"`
	Maglev                          *apiv1alpha1.LoadBalancerMaglevConfig             `json:"maglev,omitempty"`
	Random                          *apiv1alpha1.LoadBalancerRandomConfig             `json:"random,omitempty"`
	LocalityType                    *apiv1alpha1.LocalityType                         `json:"localityType,omitempty"`
	UseHostnameForHashing           *bool                                             `json:"useHostnameForHashing,omitempty"`
	CloseConnectionsOnHostSetChange *bool                                             `json:"closeConnectionsOnHostSetChange,omitempty"`
}

// LoadBalancerApplyConfiguration constructs a declarative configuration of the LoadBalancer type for use with
// apply.
func LoadBalancer() *LoadBalancerApplyConfiguration {
	return &LoadBalancerApplyConfiguration{}
}

// WithHealthyPanicThreshold sets the HealthyPanicThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HealthyPanicThreshold field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithHealthyPanicThreshold(value uint32) *LoadBalancerApplyConfiguration {
	b.HealthyPanicThreshold = &value
	return b
}

// WithUpdateMergeWindow sets the UpdateMergeWindow field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdateMergeWindow field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithUpdateMergeWindow(value v1.Duration) *LoadBalancerApplyConfiguration {
	b.UpdateMergeWindow = &value
	return b
}

// WithLeastRequest sets the LeastRequest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeastRequest field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithLeastRequest(value *LoadBalancerLeastRequestConfigApplyConfiguration) *LoadBalancerApplyConfiguration {
	b.LeastRequest = value
	return b
}

// WithRoundRobin sets the RoundRobin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoundRobin field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithRoundRobin(value *LoadBalancerRoundRobinConfigApplyConfiguration) *LoadBalancerApplyConfiguration {
	b.RoundRobin = value
	return b
}

// WithRingHash sets the RingHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RingHash field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithRingHash(value *LoadBalancerRingHashConfigApplyConfiguration) *LoadBalancerApplyConfiguration {
	b.RingHash = value
	return b
}

// WithMaglev sets the Maglev field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Maglev field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithMaglev(value apiv1alpha1.LoadBalancerMaglevConfig) *LoadBalancerApplyConfiguration {
	b.Maglev = &value
	return b
}

// WithRandom sets the Random field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Random field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithRandom(value apiv1alpha1.LoadBalancerRandomConfig) *LoadBalancerApplyConfiguration {
	b.Random = &value
	return b
}

// WithLocalityType sets the LocalityType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalityType field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithLocalityType(value apiv1alpha1.LocalityType) *LoadBalancerApplyConfiguration {
	b.LocalityType = &value
	return b
}

// WithUseHostnameForHashing sets the UseHostnameForHashing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseHostnameForHashing field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithUseHostnameForHashing(value bool) *LoadBalancerApplyConfiguration {
	b.UseHostnameForHashing = &value
	return b
}

// WithCloseConnectionsOnHostSetChange sets the CloseConnectionsOnHostSetChange field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloseConnectionsOnHostSetChange field is set to the value of the last call.
func (b *LoadBalancerApplyConfiguration) WithCloseConnectionsOnHostSetChange(value bool) *LoadBalancerApplyConfiguration {
	b.CloseConnectionsOnHostSetChange = &value
	return b
}
