// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LoadBalancerRoundRobinConfigApplyConfiguration represents a declarative configuration of the LoadBalancerRoundRobinConfig type for use
// with apply.
type LoadBalancerRoundRobinConfigApplyConfiguration struct {
	SlowStart *SlowStartApplyConfiguration `json:"slowStart,omitempty"`
}

// LoadBalancerRoundRobinConfigApplyConfiguration constructs a declarative configuration of the LoadBalancerRoundRobinConfig type for use with
// apply.
func LoadBalancerRoundRobinConfig() *LoadBalancerRoundRobinConfigApplyConfiguration {
	return &LoadBalancerRoundRobinConfigApplyConfiguration{}
}

// WithSlowStart sets the SlowStart field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SlowStart field is set to the value of the last call.
func (b *LoadBalancerRoundRobinConfigApplyConfiguration) WithSlowStart(value *SlowStartApplyConfiguration) *LoadBalancerRoundRobinConfigApplyConfiguration {
	b.SlowStart = value
	return b
}
