// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LoadBalancerMaglevConfigApplyConfiguration represents a declarative configuration of the LoadBalancerMaglevConfig type for use
// with apply.
type LoadBalancerMaglevConfigApplyConfiguration struct {
	UseHostnameForHashing *bool `json:"useHostnameForHashing,omitempty"`
}

// LoadBalancerMaglevConfigApplyConfiguration constructs a declarative configuration of the LoadBalancerMaglevConfig type for use with
// apply.
func LoadBalancerMaglevConfig() *LoadBalancerMaglevConfigApplyConfiguration {
	return &LoadBalancerMaglevConfigApplyConfiguration{}
}

// WithUseHostnameForHashing sets the UseHostnameForHashing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseHostnameForHashing field is set to the value of the last call.
func (b *LoadBalancerMaglevConfigApplyConfiguration) WithUseHostnameForHashing(value bool) *LoadBalancerMaglevConfigApplyConfiguration {
	b.UseHostnameForHashing = &value
	return b
}
