// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// McpTargetSelectorApplyConfiguration represents a declarative configuration of the McpTargetSelector type for use
// with apply.
type McpTargetSelectorApplyConfiguration struct {
	Selectors    *McpSelectorApplyConfiguration `json:"selectors,omitempty"`
	StaticTarget *McpTargetApplyConfiguration   `json:"static,omitempty"`
}

// McpTargetSelectorApplyConfiguration constructs a declarative configuration of the McpTargetSelector type for use with
// apply.
func McpTargetSelector() *McpTargetSelectorApplyConfiguration {
	return &McpTargetSelectorApplyConfiguration{}
}

// WithSelectors sets the Selectors field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selectors field is set to the value of the last call.
func (b *McpTargetSelectorApplyConfiguration) WithSelectors(value *McpSelectorApplyConfiguration) *McpTargetSelectorApplyConfiguration {
	b.Selectors = value
	return b
}

// WithStaticTarget sets the StaticTarget field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StaticTarget field is set to the value of the last call.
func (b *McpTargetSelectorApplyConfiguration) WithStaticTarget(value *McpTargetApplyConfiguration) *McpTargetSelectorApplyConfiguration {
	b.StaticTarget = value
	return b
}
