// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MetadataPathSegmentApplyConfiguration represents a declarative configuration of the MetadataPathSegment type for use
// with apply.
type MetadataPathSegmentApplyConfiguration struct {
	Key *string `json:"key,omitempty"`
}

// MetadataPathSegmentApplyConfiguration constructs a declarative configuration of the MetadataPathSegment type for use with
// apply.
func MetadataPathSegment() *MetadataPathSegmentApplyConfiguration {
	return &MetadataPathSegmentApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *MetadataPathSegmentApplyConfiguration) WithKey(value string) *MetadataPathSegmentApplyConfiguration {
	b.Key = &value
	return b
}
