// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// OpenRouterConfigApplyConfiguration represents a declarative configuration of the OpenRouterConfig type for use
// with apply.
type OpenRouterConfigApplyConfiguration struct {
	AuthToken *SingleAuthTokenApplyConfiguration `json:"authToken,omitempty"`
	Model     *string                            `json:"model,omitempty"`
}

// OpenRouterConfigApplyConfiguration constructs a declarative configuration of the OpenRouterConfig type for use with
// apply.
func OpenRouterConfig() *OpenRouterConfigApplyConfiguration {
	return &OpenRouterConfigApplyConfiguration{}
}

// WithAuthToken sets the AuthToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthToken field is set to the value of the last call.
func (b *OpenRouterConfigApplyConfiguration) WithAuthToken(value *SingleAuthTokenApplyConfiguration) *OpenRouterConfigApplyConfiguration {
	b.AuthToken = value
	return b
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *OpenRouterConfigApplyConfiguration) WithModel(value string) *OpenRouterConfigApplyConfiguration {
	b.Model = &value
	return b
}
