// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// OTelTracesSamplerApplyConfiguration represents a declarative configuration of the OTelTracesSampler type for use
// with apply.
type OTelTracesSamplerApplyConfiguration struct {
	SamplerType *apiv1alpha1.OTelTracesSamplerType `json:"type,omitempty"`
	SamplerArg  *string                            `json:"arg,omitempty"`
}

// OTelTracesSamplerApplyConfiguration constructs a declarative configuration of the OTelTracesSampler type for use with
// apply.
func OTelTracesSampler() *OTelTracesSamplerApplyConfiguration {
	return &OTelTracesSamplerApplyConfiguration{}
}

// WithSamplerType sets the SamplerType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SamplerType field is set to the value of the last call.
func (b *OTelTracesSamplerApplyConfiguration) WithSamplerType(value apiv1alpha1.OTelTracesSamplerType) *OTelTracesSamplerApplyConfiguration {
	b.SamplerType = &value
	return b
}

// WithSamplerArg sets the SamplerArg field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SamplerArg field is set to the value of the last call.
func (b *OTelTracesSamplerApplyConfiguration) WithSamplerArg(value string) *OTelTracesSamplerApplyConfiguration {
	b.SamplerArg = &value
	return b
}
