// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// ResourceDetectorApplyConfiguration represents a declarative configuration of the ResourceDetector type for use
// with apply.
type ResourceDetectorApplyConfiguration struct {
	EnvironmentResourceDetector *apiv1alpha1.EnvironmentResourceDetectorConfig `json:"environmentResourceDetector,omitempty"`
}

// ResourceDetectorApplyConfiguration constructs a declarative configuration of the ResourceDetector type for use with
// apply.
func ResourceDetector() *ResourceDetectorApplyConfiguration {
	return &ResourceDetectorApplyConfiguration{}
}

// WithEnvironmentResourceDetector sets the EnvironmentResourceDetector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnvironmentResourceDetector field is set to the value of the last call.
func (b *ResourceDetectorApplyConfiguration) WithEnvironmentResourceDetector(value apiv1alpha1.EnvironmentResourceDetectorConfig) *ResourceDetectorApplyConfiguration {
	b.EnvironmentResourceDetector = &value
	return b
}
