// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RetryPolicyApplyConfiguration represents a declarative configuration of the RetryPolicy type for use
// with apply.
type RetryPolicyApplyConfiguration struct {
	RetryBackOff *BackoffStrategyApplyConfiguration `json:"retryBackOff,omitempty"`
	NumRetries   *uint32                            `json:"numRetries,omitempty"`
}

// RetryPolicyApplyConfiguration constructs a declarative configuration of the RetryPolicy type for use with
// apply.
func RetryPolicy() *RetryPolicyApplyConfiguration {
	return &RetryPolicyApplyConfiguration{}
}

// WithRetryBackOff sets the RetryBackOff field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryBackOff field is set to the value of the last call.
func (b *RetryPolicyApplyConfiguration) WithRetryBackOff(value *BackoffStrategyApplyConfiguration) *RetryPolicyApplyConfiguration {
	b.RetryBackOff = value
	return b
}

// WithNumRetries sets the NumRetries field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NumRetries field is set to the value of the last call.
func (b *RetryPolicyApplyConfiguration) WithNumRetries(value uint32) *RetryPolicyApplyConfiguration {
	b.NumRetries = &value
	return b
}
