// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// SamplerApplyConfiguration represents a declarative configuration of the Sampler type for use
// with apply.
type SamplerApplyConfiguration struct {
	AlwaysOn *apiv1alpha1.AlwaysOnConfig `json:"alwaysOnConfig,omitempty"`
}

// SamplerApplyConfiguration constructs a declarative configuration of the Sampler type for use with
// apply.
func Sampler() *SamplerApplyConfiguration {
	return &SamplerApplyConfiguration{}
}

// WithAlwaysOn sets the AlwaysOn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AlwaysOn field is set to the value of the last call.
func (b *SamplerApplyConfiguration) WithAlwaysOn(value apiv1alpha1.AlwaysOnConfig) *SamplerApplyConfiguration {
	b.AlwaysOn = &value
	return b
}
