// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SlowStartApplyConfiguration represents a declarative configuration of the SlowStart type for use
// with apply.
type SlowStartApplyConfiguration struct {
	Window           *v1.Duration `json:"window,omitempty"`
	Aggression       *string      `json:"aggression,omitempty"`
	MinWeightPercent *uint32      `json:"minWeightPercent,omitempty"`
}

// SlowStartApplyConfiguration constructs a declarative configuration of the SlowStart type for use with
// apply.
func SlowStart() *SlowStartApplyConfiguration {
	return &SlowStartApplyConfiguration{}
}

// WithWindow sets the Window field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Window field is set to the value of the last call.
func (b *SlowStartApplyConfiguration) WithWindow(value v1.Duration) *SlowStartApplyConfiguration {
	b.Window = &value
	return b
}

// WithAggression sets the Aggression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Aggression field is set to the value of the last call.
func (b *SlowStartApplyConfiguration) WithAggression(value string) *SlowStartApplyConfiguration {
	b.Aggression = &value
	return b
}

// WithMinWeightPercent sets the MinWeightPercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinWeightPercent field is set to the value of the last call.
func (b *SlowStartApplyConfiguration) WithMinWeightPercent(value uint32) *SlowStartApplyConfiguration {
	b.MinWeightPercent = &value
	return b
}
