// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TLSFilesApplyConfiguration represents a declarative configuration of the TLSFiles type for use
// with apply.
type TLSFilesApplyConfiguration struct {
	TLSCertificate *string `json:"tlsCertificate,omitempty"`
	TLSKey         *string `json:"tlsKey,omitempty"`
	RootCA         *string `json:"rootCA,omitempty"`
}

// TLSFilesApplyConfiguration constructs a declarative configuration of the TLSFiles type for use with
// apply.
func TLSFiles() *TLSFilesApplyConfiguration {
	return &TLSFilesApplyConfiguration{}
}

// WithTLSCertificate sets the TLSCertificate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSCertificate field is set to the value of the last call.
func (b *TLSFilesApplyConfiguration) WithTLSCertificate(value string) *TLSFilesApplyConfiguration {
	b.TLSCertificate = &value
	return b
}

// WithTLSKey sets the TLSKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSKey field is set to the value of the last call.
func (b *TLSFilesApplyConfiguration) WithTLSKey(value string) *TLSFilesApplyConfiguration {
	b.TLSKey = &value
	return b
}

// WithRootCA sets the RootCA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RootCA field is set to the value of the last call.
func (b *TLSFilesApplyConfiguration) WithRootCA(value string) *TLSFilesApplyConfiguration {
	b.RootCA = &value
	return b
}
