// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TracingProviderApplyConfiguration represents a declarative configuration of the TracingProvider type for use
// with apply.
type TracingProviderApplyConfiguration struct {
	OpenTelemetry *OpenTelemetryTracingConfigApplyConfiguration `json:"openTelemetry,omitempty"`
}

// TracingProviderApplyConfiguration constructs a declarative configuration of the TracingProvider type for use with
// apply.
func TracingProvider() *TracingProviderApplyConfiguration {
	return &TracingProviderApplyConfiguration{}
}

// WithOpenTelemetry sets the OpenTelemetry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpenTelemetry field is set to the value of the last call.
func (b *TracingProviderApplyConfiguration) WithOpenTelemetry(value *OpenTelemetryTracingConfigApplyConfiguration) *TracingProviderApplyConfiguration {
	b.OpenTelemetry = value
	return b
}
