// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	typedapiv1alpha1 "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/api/v1alpha1"
)

// fakeBackendConfigPolicies implements BackendConfigPolicyInterface
type fakeBackendConfigPolicies struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.BackendConfigPolicy, *v1alpha1.BackendConfigPolicyList, *apiv1alpha1.BackendConfigPolicyApplyConfiguration]
	Fake *FakeGatewayV1alpha1
}

func newFakeBackendConfigPolicies(fake *FakeGatewayV1alpha1, namespace string) typedapiv1alpha1.BackendConfigPolicyInterface {
	return &fakeBackendConfigPolicies{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.BackendConfigPolicy, *v1alpha1.BackendConfigPolicyList, *apiv1alpha1.BackendConfigPolicyApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("backendconfigpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("BackendConfigPolicy"),
			func() *v1alpha1.BackendConfigPolicy { return &v1alpha1.BackendConfigPolicy{} },
			func() *v1alpha1.BackendConfigPolicyList { return &v1alpha1.BackendConfigPolicyList{} },
			func(dst, src *v1alpha1.BackendConfigPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.BackendConfigPolicyList) []*v1alpha1.BackendConfigPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.BackendConfigPolicyList, items []*v1alpha1.BackendConfigPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
