// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type BackendExpansion interface{}

type BackendConfigPolicyExpansion interface{}

type DirectResponseExpansion interface{}

type GatewayExtensionExpansion interface{}

type GatewayParametersExpansion interface{}

type HTTPListenerPolicyExpansion interface{}

type TrafficPolicyExpansion interface{}
