// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type BackendExpansion interface{}

type DirectResponseExpansion interface{}

type GatewayParametersExpansion interface{}

type HTTPListenerPolicyExpansion interface{}

type RoutePolicyExpansion interface{}
