# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extproto/ext.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65xtproto/ext.proto\x12\x08\x65xtproto\x1a google/protobuf/descriptor.proto:/\n\x08hash_all\x12\x1c.google.protobuf.FileOptions\x18\xd7N \x01(\x08:0\n\tequal_all\x12\x1c.google.protobuf.FileOptions\x18\xd8N \x01(\x08:0\n\tmerge_all\x12\x1c.google.protobuf.FileOptions\x18\xd9N \x01(\x08:0\n\tclone_all\x12\x1c.google.protobuf.FileOptions\x18\xdaN \x01(\x08:4\n\x0cskip_hashing\x12\x1d.google.protobuf.FieldOptions\x18\xd7N \x01(\x08:4\n\x0cskip_merging\x12\x1d.google.protobuf.FieldOptions\x18\xd8N \x01(\x08:1\n\tsensitive\x12\x1d.google.protobuf.FieldOptions\x18\xd9N \x01(\x08::\n\x12skip_merging_oneof\x12\x1d.google.protobuf.OneofOptions\x18\xd8N \x01(\x08\x42,Z*github.com/solo-io/protoc-gen-ext/extproto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extproto.ext_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/solo-io/protoc-gen-ext/extproto'
# @@protoc_insertion_point(module_scope)
