apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: gwtest
spec:
  gatewayClassName: kgateway
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-route
  namespace: gwtest
spec:
  parentRefs:
    - name: example-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /test
      backendRefs:
        - name: test-service
          port: 80
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: test-ratelimit
  namespace: gwtest
spec:
  type: RateLimit
  rateLimit:
    domain: test-domain
    grpcService:
      backendRef:
        name: test-service
        port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: gwtest
spec:
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      appProtocol: h2c
  selector:
    app: test-service
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: invalid-global-ratelimit-fields
  namespace: gwtest
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: test-route
  rateLimit:
    global:
      extensionRef:
        name: test-ratelimit
      descriptors:
        - entries:
            - type: Header
              header: ""  # Proto validation error: header name cannot be empty
        - entries:
            - type: Generic
              generic:
                key: ""    # Proto validation error: key cannot be empty
                value: ""  # Proto validation error: value cannot be empty
