apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: default
spec:
  gatewayClassName: example-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: default
spec:
  parentRefs:
    - name: example-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /c1
      backendRefs:
        - name: backend
          port: 3000
      sessionPersistence:
        sessionName: Session-A
        type: Cookie
        absoluteTimeout: 10s
        cookieConfig:
          lifetimeType: Permanent
    - matches:
        - path:
            type: PathPrefix
            value: /c2
      backendRefs:
        - name: backend
          port: 3000
      sessionPersistence:
        sessionName: Session-B
        type: Cookie
        cookieConfig:
          lifetimeType: Permanent 
    - matches:
        - path:
            type: PathPrefix
            value: /c3
      backendRefs:
        - name: backend
          port: 3000
      sessionPersistence:
        sessionName: Session-B
        type: Cookie
        cookieConfig:
          lifetimeType: Session

---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: example-grpc-route
  namespace: default
spec:
  parentRefs:
    - name: example-gateway
  rules:
    - matches:
        - method:
            type: Exact
            method: foo
      backendRefs:
        - name: backend
          port: 3000
      sessionPersistence:
        sessionName: Session-A
        type: Cookie
        absoluteTimeout: 10s
        cookieConfig:
          lifetimeType: Permanent
    - matches:
        - method:
            type: Exact
            method: foo2
      backendRefs:
        - name: backend
          port: 3000
      sessionPersistence:
        sessionName: Session-B
        type: Cookie
        cookieConfig:
          lifetimeType: Permanent 
    - matches:
        - method:
            type: Exact
            method: foo3
      backendRefs:
        - name: backend
          port: 3000
      sessionPersistence:
        sessionName: Session-B
        type: Cookie
        cookieConfig:
          lifetimeType: Session
