openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /health:
    get:
      summary: Health
      operationId: health_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /shutdown:
    get:
      summary: Shutdown
      operationId: shutdown_shutdown_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
webhooks:
  /request:
    post:
      tags:
      - Webhooks
      summary: Process Prompts
      description: "This webhook will be called for every request before sending the\
        \ prompts to the LLM. The 'role' and 'content' are extracted from the prompts\
        \ into the PromptMessages json object regardless of the API format from various\
        \ providers.\n\n\nThree types of responses are possible by returning one of\
        \ the follow three json objects:\n\n\n    - PassAction  : Indicates that no\
        \ action is taken for the prompts and it is allow to be send to the LLM\n\
        \    - MaskAction  : Indicates that some information are masked in the prompt\
        \ and it needs to be updated before sending to the LLM\n                 \
        \   The PromptMessages json object of the request can be modified in place\
        \ and send back in the body field of the\n                    response. The\
        \ number of messages inside PromptMessages MUST be the same as the request\
        \ in this webhook call. \n                    So, if the content needs to\
        \ be deleted, an empty content field need to be set.\n    - RejectAction:\
        \ Indicates that the request should be rejected with the specific status code\
        \ and response message. The request\n                    will not be sent\
        \ to the LLM."
      operationId: process_prompts_request_post
      parameters:
      - required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: X-Action
        name: x-action
        in: header
      - required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: X-Response-Message
        name: x-response-message
        in: header
      - required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: X-Status-Code
        name: x-status-code
        in: header
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GuardrailsPromptRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GuardrailsPromptResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /response:
    post:
      tags:
      - Webhooks
      summary: Process Responses
      description: "This webhook will be called for every response from the LLM before\
        \ sending back to the user. The 'role' and 'content' are extracted from the\
        \ prompts into the ResponseChoices json object regardless of the API format\
        \ from various providers.\n\n\nFor streaming responses from the LLM, this\
        \ webhook will be called multiple times for a single response. The AI gateway\
        \ will buffer and detect the semantic boundary of the content before making\
        \ the webhook call.\n\n\nTwo types of responses are possible by returning\
        \ one of the follow two json objects:\n\n\n    - PassAction: Indicates that\
        \ no action is taken for the response and it is allow to be send to the user.\n\
        \    - MaskAction: Indicates that some information are masked in the response\
        \ and it needs to be updated before sending\n                  to the user.\
        \ The ResponseChoices json object from this webhook call can be modified in\
        \ place and send\n                  back in the body field in the response.\n\
        \                  The number of choices inside ResponseChoices MUST be the\
        \ same as the request in this webhook call.\n                  So, if the\
        \ content needs to be deleted, an empty content field need to be set."
      operationId: process_responses_response_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GuardrailsResponseRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GuardrailsResponseResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    GuardrailsPromptRequest:
      properties:
        body:
          $ref: '#/components/schemas/PromptMessages'
          description: body contains the object which is a list of the Message JSON
            objects from the prompts in the request
      type: object
      required:
      - body
      title: GuardrailsPromptRequest
      description: GuardrailsPromptRequest is the request model for the Guardrails
        prompt API.
    GuardrailsPromptResponse:
      properties:
        action:
          anyOf:
          - $ref: '#/components/schemas/PassAction'
          - $ref: '#/components/schemas/MaskAction'
          - $ref: '#/components/schemas/RejectAction'
          title: Action
          description: "\n        action is the action to be taken based on the request.\n\
            \        The following actions are available on the response: \n     \
            \   - PassAction: No action is required.\n        - MaskAction: Mask the\
            \ response body.\n        - RejectAction: Reject the request.\n      \
            \  "
      type: object
      required:
      - action
      title: GuardrailsPromptResponse
      description: GuardrailsPromptResponse is the response model for the Guardrails
        prompt API.
    GuardrailsResponseRequest:
      properties:
        body:
          $ref: '#/components/schemas/ResponseChoices-Input'
          description: body contains the object with a list of Choice that contains
            the response content from the LLM.
      type: object
      required:
      - body
      title: GuardrailsResponseRequest
      description: GuardrailsResponseRequest is the request model for the Guardrails
        response API.
    GuardrailsResponseResponse:
      properties:
        action:
          anyOf:
          - $ref: '#/components/schemas/PassAction'
          - $ref: '#/components/schemas/MaskAction'
          title: Action
          description: "\n        action is the action to be taken based on the request.\n\
            \        The following actions are available on the response: \n     \
            \   - PassAction: No action is required.\n        - MaskAction: Mask the\
            \ response body.\n        "
      type: object
      required:
      - action
      title: GuardrailsResponseResponse
      description: GuardrailsResponseResponse is the response model for the Guardrails
        response API.
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    MaskAction:
      properties:
        body:
          anyOf:
          - $ref: '#/components/schemas/PromptMessages'
          - $ref: '#/components/schemas/ResponseChoices-Output'
          title: Body
          description: body contains the modified messages that masked out some of
            the original contents. When used in a GuardrailPromptResponse, this should
            be PromptMessages. When used in GuardrailResponseResponse, this should
            be ResponseChoices
        reason:
          anyOf:
          - type: string
          - type: 'null'
          title: Reason
          description: reason is a human readable string that explains the reason
            for the action.
      type: object
      required:
      - body
      title: MaskAction
      description: 'MaskAction is the response model for the Mask action which indicates
        the message has been modified.

        This can be used in GuardrailsPromptResponse or GuardrailsResponseResponse
        when responding to a GuardrailsPromptRequest or a GuardrailsResponseRequest
        respectively'
    Message:
      properties:
        role:
          type: string
          title: Role
          description: The role associated to the content in this message.
          examples:
          - Assistant
        content:
          type: string
          title: Content
          description: The content text for this message.
          examples:
          - How can I help you today?
      type: object
      required:
      - role
      - content
      title: Message
      description: Message contains the text prompts for a request to the LLM or the
        response content from the LLM.
    PassAction:
      properties:
        reason:
          anyOf:
          - type: string
          - type: 'null'
          title: Reason
          description: reason is a human readable string that explains the reason
            for the action.
      type: object
      title: PassAction
      description: PassAction is the response model for the Pass action which indicate
        no modification is done to the messages.
    PromptMessages:
      properties:
        messages:
          items:
            $ref: '#/components/schemas/Message'
          type: array
          title: Messages
          description: List of prompt messages including role and content.
          examples:
          - - content: How can I help you?
              role: Assistant
            - content: What is 1 + 2?
              role: User
      type: object
      title: PromptMessages
      description: PromptMessages contains a list of prompt messages in a request
        to the LLM
    RejectAction:
      properties:
        body:
          type: string
          title: Body
          description: body is the rejection message that will be used for HTTP error
            response body.
        status_code:
          type: integer
          title: Status Code
          description: status_code is the HTTP status code to be returned in the HTTP
            error response.
        reason:
          anyOf:
          - type: string
          - type: 'null'
          title: Reason
          description: reason is a human readable string that explains the reason
            for the action.
      type: object
      required:
      - body
      - status_code
      title: RejectAction
      description: 'RejectAction is the response model for the Reject action which
        indicate the request should be rejected.

        This action will cause a HTTP error response to be sent back to the end-user.'
    ResponseChoice:
      properties:
        message:
          $ref: '#/components/schemas/Message'
          description: message contains the role and text content of the response
            from the LLM model.
          examples:
          - content: 1 + 2 is 3
            role: Assistant
      type: object
      required:
      - message
      title: ResponseChoice
      description: ResponseChoice is a single choice of the chat completion response
        text from the LLM
    ResponseChoices-Input:
      properties:
        choices:
          items:
            $ref: '#/components/schemas/ResponseChoice'
          type: array
          title: Choices
          description: list of possible independent responses from the LLM
          examples:
          - - message:
                content: 1 + 2 is 3
                role: Assistant
            - message:
                content: The result of adding 1 to 2 is 3
                role: Assistant
      type: object
      title: ResponseChoices
      description: ResponseChoices contains a list of response choices from the LLM.
        Each choice represent a separate independent response.
    ResponseChoices-Output:
      properties:
        choices:
          items:
            $ref: '#/components/schemas/ResponseChoice'
          type: array
          title: Choices
          description: list of possible independent responses from the LLM
          examples:
          - - message:
                content: 1 + 2 is 3
                role: Assistant
            - message:
                content: The result of adding 1 to 2 is 3
                role: Assistant
      type: object
      title: ResponseChoices
      description: ResponseChoices contains a list of response choices from the LLM.
        Each choice represent a separate independent response.
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
