from google.protobuf import descriptor_pb2 as _descriptor_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
DISALLOWED_BY_DEFAULT_FIELD_NUMBER: _ClassVar[int]
disallowed_by_default: _descriptor.FieldDescriptor
DEPRECATED_AT_MINOR_VERSION_FIELD_NUMBER: _ClassVar[int]
deprecated_at_minor_version: _descriptor.FieldDescriptor
DISALLOWED_BY_DEFAULT_ENUM_FIELD_NUMBER: _ClassVar[int]
disallowed_by_default_enum: _descriptor.FieldDescriptor
DEPRECATED_AT_MINOR_VERSION_ENUM_FIELD_NUMBER: _ClassVar[int]
deprecated_at_minor_version_enum: _descriptor.FieldDescriptor
