# This test contains a route that has multiple TrafficPolicies targeting it.
#
# The expected output must contain the merged policies
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: infra
spec:
  gatewayClassName: example-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: infra
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - name: rule0
    backendRefs:
    - name: example-svc
      port: 80
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.kgateway.dev
        kind: TrafficPolicy
        name: extensionref-policy
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: extensionref-policy
  namespace: infra
spec:
  cors:
    allowOrigins:
    - "https://example.com"
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: policy-with-section-name
  namespace: infra
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: example-route
    sectionName: rule0
  # cors will be ignored in favor of extensionref-policy
  cors:
    allowOrigins:
    - "https://ignored.com"
  transformation:
    response:
      add:
      - name: abc
        value: custom-value-abc
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: policy-without-section-name
  namespace: infra
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: example-route
  rateLimit:
    local:
      tokenBucket:
        maxTokens: 99
        tokensPerFill: 1
        fillInterval: 33s
  # transformation will be ignored in favor of policy-with-section-name
  transformation:
    response:
      add:
      - name: ignored
        value: ignored
---
apiVersion: v1
kind: Service
metadata:
  name: example-svc
  namespace: infra
spec:
  selector:
    test: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: test